[theme]
primaryColor = "#E30613"
backgroundColor = "#F4F5F7"
secondaryBackgroundColor = "#FFFFFF"
textColor = "#202124"
font = "sans serif"

[server]
maxUploadSize = 500

[browser]
gatherUsageStats = false
